name: Publish Package to GitHub Packages (next)
on:
  push:
    branches:
      - alpha
      - next
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - run: npm install
      - run: npm run build
      - run: npm run package:prepare
      - name: Configure GitHub Packages auth
        run: |
          cat <<'EOFNPM' > "$RUNNER_TEMP/github-packages.npmrc"
          @nodeknit:registry=https://npm.pkg.github.com
          //npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}
          always-auth=true
          EOFNPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run package:version
        env:
          PACKAGE_CHANNEL: ${{ github.ref_name }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_USERCONFIG: ${{ runner.temp }}/github-packages.npmrc
      - run: npm publish --tag ${{ github.ref_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_USERCONFIG: ${{ runner.temp }}/github-packages.npmrc
        working-directory: ./dist
